version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: todo:latest
    command: ["python manage.py runserver 0.0.0.0:8000"]
    ports:
      - 8000:8000
    restart: always
